# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_request', models.TextField(max_length=512)),
                ('raw_response', models.TextField(max_length=512)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('correlation_id', models.CharField(editable=False, max_length=32, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
