# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_opp', '0002_auto_20161209_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_id',
            field=models.CharField(editable=False, max_length=48, null=True, unique=True),
        ),
    ]
