# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_opp', '0004_transaction_result_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='correlation_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
